steps:
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['install']
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/steadfast-helix-214610/nginx:$REVISION_ID", "docker/"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/steadfast-helix-214610/nginx:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/nginx'
  - 'nginx=gcr.io/steadfast-helix-214610/nginx:$REVISION_ID'
  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster1'
